In [1]:
import os
import pickle
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from videoutils import make_animation

In [2]:
train_videos = pickle.load(open("train_structure.pkl", "rb"))
test_videos = pickle.load(open("test_structure.pkl", "rb"))

In [3]:
train_videos.keys()

dict_keys(['RoadAccidents', 'Arson', 'Shoplifting', 'Stealing', 'Burglary', 'NormalVideos', 'Fighting', 'Vandalism', 'Explosion', 'Arrest', 'Abuse', 'Robbery', 'Assault', 'Shooting'])

In [4]:
def counter(dataset):
    frames_count = []

    for class_name, videos in dataset.items():
        for video_name, info in videos.items():
            row = {"vid_name": video_name}
            row["label"] = class_name
            row["num_frames"] = info["num_frames"]
            frames_count.append(row)
    
    return pd.DataFrame(frames_count)

## Train dataset class statistics

In [5]:
train_df = counter(train_videos)
train_df.to_csv("train_df.csv", sep=';')
train_df.describe()

         num_frames
count   1610.000000
mean     786.549689
std     3547.016891
min       11.000000
25%      117.000000
50%      222.500000
75%      449.750000
max    97651.000000

In [6]:
train_df[train_df["num_frames"]==97651]

             vid_name         label  num_frames
382  Normal_Videos308  NormalVideos       97651

In [7]:
train_df.groupby("label")["num_frames"].mean()

label
Abuse             397.416667
Arrest            586.600000
Arson             595.634146
Assault           220.425532
Burglary          454.068966
Explosion         646.655172
Fighting          548.533333
NormalVideos     1184.710000
RoadAccidents     184.929134
Robbery           286.158621
Shooting          264.444444
Shoplifting       856.379310
Stealing          471.600000
Vandalism         302.800000
Name: num_frames, dtype: float64

In [8]:
# train_df[train_df["num_frames"]==11]
frames_list = train_videos["RoadAccidents"]["RoadAccidents027"]["frames"]
make_animation(frames_list, 100)

## Test dataset class statistics

In [9]:
test_df = counter(test_videos)
test_df.to_csv("test_df.csv", sep=';')
test_df.describe()

         num_frames
count    290.000000
mean     383.820690
std      954.616644
min       16.000000
25%      107.250000
50%      179.500000
75%      360.000000
max    10800.000000

In [10]:
test_df[test_df["num_frames"]==10800]

             vid_name         label  num_frames
72  Normal_Videos_924  NormalVideos       10800
76  Normal_Videos_935  NormalVideos       10800

In [11]:
test_df.groupby("label")["num_frames"].mean()

label
Abuse            148.500000
Arrest           673.000000
Arson            310.333333
Assault          885.666667
Burglary         589.000000
Explosion        310.000000
Fighting         246.200000
NormalVideos     433.013333
RoadAccidents    115.782609
Robbery          167.000000
Shooting         331.739130
Shoplifting      363.000000
Stealing         396.800000
Vandalism        222.200000
Name: num_frames, dtype: float64

In [12]:
# test_df[test_df["num_frames"]==16]
frames_list = train_videos["Explosion"]["Explosion046"]["frames"]
#make_animation(frames_list, 100)
len(frames_list)

14190